{{- if .Values.matrix_secret.deploy.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-%s" (include "matrix-appservice-webhooks.fullname" .) "matrix") .Values.matrix_secret.name_override | quote }}
  labels:
    {{- include "matrix-appservice-webhooks.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ required "If matrix_secret.deploy.enabled is set to true, matrix_secret.deploy.username and matrix_secret.deploy.password are required" .Values.matrix_secret.deploy.username | b64enc | quote }}
  password: {{ required "If matrix_secret.deploy.enabled is set to true, matrix_secret.deploy.username and matrix_secret.deploy.password are required" .Values.matrix_secret.deploy.password | b64enc | quote }}
{{- end }}

