{{- if and .Values.persistence.config.enabled (not .Values.persistence.config.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "radarr.fullname" . }}-config
  labels:
    app: {{ template "radarr.name" . }}
    chart: {{ template "radarr.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- if .Values.extraLabels }}
    {{ toYaml .Values.extraLabels | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.config.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size | quote }}
  {{- if .Values.persistence.config.storageClass }}
  {{- if (eq "-" .Values.persistence.config.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.config.storageClass }}"
  {{- end }}
  {{- end }}
{{- end }}
