apiVersion: v1
kind: Service
metadata:
  {{- if .Values.service.annotations }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
  name: {{ template "radarr.fullname" . }}
  labels:
    app: {{ template "radarr.name" . }}
    chart: {{ template "radarr.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- if .Values.extraLabels }}
    {{ toYaml .Values.extraLabels | nindent 4 }}
    {{- end }}
spec:
  clusterIP: {{ .Values.service.clusterIP | quote }}
  {{- if .Values.service.externalIPs }}
  externalIPs:
    {{ toYaml .Values.service.externalIPs | nindent 4 }}
  {{- end }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP | quote }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{ toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.httpPort }}
      targetPort: http
  selector:
    app: {{ template "radarr.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
